// <auto-generated />
using System;
using System.Collections.Generic;
using GidaKoprusu.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GidaKoprusu.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GidaKoprusu.Api.Data.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<List<string>>("Allergens")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("allergens");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal>("Co2ReductionKg")
                        .HasColumnType("numeric")
                        .HasColumnName("co2_reduction_kg");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PickupEndTime")
                        .HasColumnType("text")
                        .HasColumnName("pickup_end_time");

                    b.Property<string>("PickupStartTime")
                        .HasColumnType("text")
                        .HasColumnName("pickup_start_time");

                    b.Property<int>("PortionsAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("portions_available");

                    b.Property<int>("PortionsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("portions_total");

                    b.Property<decimal>("PriceDiscounted")
                        .HasColumnType("numeric")
                        .HasColumnName("price_discounted");

                    b.Property<decimal>("PriceOriginal")
                        .HasColumnType("numeric")
                        .HasColumnName("price_original");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("discounted")
                        .HasColumnName("type");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_listings_organisation_id");

                    b.ToTable("listings", t =>
                        {
                            t.HasCheckConstraint("ck_listings_portions_available", "portions_available >= 0");

                            t.HasCheckConstraint("ck_listings_portions_total", "portions_total > 0");

                            t.HasCheckConstraint("ck_listings_status", "status in ('active', 'archived')");

                            t.HasCheckConstraint("ck_listings_type", "type in ('free', 'discounted', 'bulk')");
                        });
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.Organisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Cover")
                        .HasColumnType("text")
                        .HasColumnName("cover");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("review_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDonatedKg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_donated_kg");

                    b.Property<int>("TrustScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("trust_score");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.ToTable("organisations", t =>
                        {
                            t.HasCheckConstraint("ck_organisations_kind", "kind in ('business', 'ngo')");

                            t.HasCheckConstraint("ck_organisations_status", "status in ('pending', 'active', 'suspended')");

                            t.HasCheckConstraint("ck_organisations_trust_score", "trust_score between 0 and 100");
                        });
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.OtpCode", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.HasKey("Email")
                        .HasName("pk_otp_codes");

                    b.ToTable("otp_codes");
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Co2Kg")
                        .HasColumnType("numeric")
                        .HasColumnName("co2_kg");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<DateTime?>("ListingCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("listing_created_at");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("ListingTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("listing_title");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organisation_id");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("paid_amount");

                    b.Property<string>("PickupCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pickup_code");

                    b.Property<string>("PickupEndTime")
                        .HasColumnType("text")
                        .HasColumnName("pickup_end_time");

                    b.Property<string>("PickupStartTime")
                        .HasColumnType("text")
                        .HasColumnName("pickup_start_time");

                    b.Property<int>("PortionCount")
                        .HasColumnType("integer")
                        .HasColumnName("portion_count");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_token");

                    b.Property<decimal>("SavedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("saved_amount");

                    b.Property<decimal>("SavedKg")
                        .HasColumnType("numeric")
                        .HasColumnName("saved_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("confirmed")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_reservations_listing_id");

                    b.HasIndex("QrToken")
                        .IsUnique()
                        .HasDatabaseName("ix_reservations_qr_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reservations_user_id");

                    b.HasIndex("OrganisationId", "PickupCode")
                        .IsUnique()
                        .HasDatabaseName("ix_reservations_organisation_id_pickup_code");

                    b.ToTable("reservations", t =>
                        {
                            t.HasCheckConstraint("ck_reservations_portion_count", "portion_count > 0");

                            t.HasCheckConstraint("ck_reservations_status", "status in ('confirmed', 'completed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organisation_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_reservation_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.HasIndex("OrganisationId", "CreatedAt")
                        .HasDatabaseName("ix_reviews_organisation_id_created_at");

                    b.ToTable("reviews", t =>
                        {
                            t.HasCheckConstraint("ck_reviews_comment", "char_length(comment) <= 500");

                            t.HasCheckConstraint("ck_reviews_rating", "rating between 1 and 5");
                        });
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("OrganisationId")
                        .HasColumnType("text")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_users_organisation_id");

                    b.ToTable("users", t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role in ('buyer', 'business', 'ngo', 'admin')");
                        });
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.Listing", b =>
                {
                    b.HasOne("GidaKoprusu.Api.Data.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listings_organisations_organisation_id");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.Reservation", b =>
                {
                    b.HasOne("GidaKoprusu.Api.Data.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reservations_listings_listing_id");

                    b.HasOne("GidaKoprusu.Api.Data.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_organisations_organisation_id");

                    b.HasOne("GidaKoprusu.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_users_user_id");

                    b.Navigation("Listing");

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.Review", b =>
                {
                    b.HasOne("GidaKoprusu.Api.Data.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_organisations_organisation_id");

                    b.HasOne("GidaKoprusu.Api.Data.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_reservations_reservation_id");

                    b.HasOne("GidaKoprusu.Api.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_user_id");

                    b.Navigation("Organisation");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GidaKoprusu.Api.Data.User", b =>
                {
                    b.HasOne("GidaKoprusu.Api.Data.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_organisations_organisation_id");

                    b.Navigation("Organisation");
                });
#pragma warning restore 612, 618
        }
    }
}
